Bouncibility: Entity::BallFactory Class Reference
Entity::BallFactory Class Reference
#include <EntityManager.h>
Private Member Functions
WorldEntity & loadEntity (const std::string &XMLFilename)
Each child class of EntityFactory should implement the way it wishes to load its WorldEntity object based on the type it is.
Detailed Description
Definition at line 34 of file EntityManager.h.
Member Function Documentation
WorldEntity & Entity::BallFactory::loadEntity (const std::string & XMLFilename) [private, virtual]
Each child class of EntityFactory should implement the way it wishes to load its WorldEntity object based on the type it is.
Implements Entity::EntityFactory.
Definition at line 14 of file EntityManager.cpp.
References LevelManager::getPhysicsWorld(), LevelManager::getSceneManager(), material, WorldEntity::setBodyMaterial(), WorldEntity::setMesh(), WorldEntity::setPhysicsBody(), WorldEntity::setSceneNode(), and smgr.
{
        std::cout << "in ball factory opening xml file " << XMLFilename << "\n";
        irr::io::IrrXMLReader* xml = irr::io::createIrrXMLReader(XMLFilename.c_str());
        // strings for storing the data we want to get out of the file
        std::string name;
        std::string meshFile;
        std::string textureFile;
        std::string startState;
        while(xml && xml->read())
        {
                switch(xml->getNodeType())
                {
                case EXN_TEXT:
                        //No text nodes
                        break;
                case EXN_ELEMENT:
                        if (!strcmp("ball", xml->getNodeName())){
                                name = xml->getAttributeValue("name");
                                meshFile = xml->getAttributeValue("mesh");
                                textureFile = xml->getAttributeValue("texture");
                                startState = xml->getAttributeValue("start_state");
                        }
                        break;
                }
        }
        irr::scene::ISceneManager* smgr = LevelManager::getSceneManager();
        //irr::scene::IAnimatedMesh* mesh = smgr->getMesh(meshFile.c_str());
        //irr::scene::IAnimatedMeshSceneNode* node = smgr->addAnimatedMeshSceneNode( mesh );
        irr::scene::ISceneNode* node = smgr->addSphereSceneNode(22);
        if (node)
        {
                node->setScale(core::vector3df(1.0f,1.0f,1.0f));
                node->setMaterialFlag(irr::video::EMF_LIGHTING, false);
                //node->setMD2Animation ( irr::scene::EMAT_STAND );
                //node->setMaterialTexture( 0, LevelManager::getDriver()->getTexture(textureFile.c_str()) );
        }
        node->setPosition(core::vector3df(-150,50,0));
        WorldEntity* entity = new Ball();
        //create physics for ball
        entity->setMesh(NULL);
        irr::newton::IMaterial* material = LevelManager::getPhysicsWorld()->createMaterial();
        entity->setBodyMaterial(material);
        irr::newton::SBodyFromNode physics_node;
        physics_node.Node = node;
        physics_node.Type = irr::newton::EBT_PRIMITIVE_ELLIPSOID;
        irr::newton::ICharacterController* body = LevelManager::getPhysicsWorld()->createCharacterController(LevelManager::getPhysicsWorld()->createBody(physics_node));
        body->setRotationUpdate(true);
        body->setContinuousCollisionMode(true);
        body->setMaterial(material);
        body->addForceContinuous(irr::core::vector3df(0,-2.0f,0));
        entity->setPhysicsBody(body);
        entity->setSceneNode(node);
        //entity->changeState(startState)
        return *entity;
}
The documentation for this class was generated from the following files:
C:/Users/chase/Desktop/game2/edge/bouncibility/include/EntityManager.h
C:/Users/chase/Desktop/game2/edge/bouncibility/src/EntityManager.cpp