Bouncibility: Entity::Loader Class Reference
Entity::Loader Class Reference
Loader is used by EntityManager. It keeps track of the factories for each type. Types are currently hard coded.
#include <EntityManager.h>
Private Member Functions
WorldEntity & loadEntity (EntityInfo *entityInfo)
Creates the worldEntity using the provided factory and returns a reference to it.
EntityFactory * getFactory (const std::string &type)
Returns the factory pointer given a type name string. This should be used by EntityManager while loading Entities in.
bool registerFactory (const std::string &type, EntityFactory *factory)
Registers a factory and type into the Loader. These are hard coded in the EntityManager and might always be. Factories must be loaded before that type can be created. There should not be multiple factories for a single type. The first type given will be the only one registered. Once a factory is loaded it can be forgotten about and will be deleted by the Loader.
bool remove (const std::string &type)
Removes the factory associated with the given type. Returns false if that type did not have a factory.
void removeAll ()
Removes all registered factories and frees up their memory.
Loader ()
~Loader ()
Private Attributes
TypeFactoryMap m_FactoryMap
Friends
class ::EntityManager
Detailed Description
Loader is used by EntityManager. It keeps track of the factories for each type. Types are currently hard coded.
Definition at line 40 of file EntityManager.h.
Constructor & Destructor Documentation
Entity::Loader::Loader () [private]
Definition at line 90 of file EntityManager.cpp.
                    {
}
Entity::Loader::~Loader () [private]
Definition at line 93 of file EntityManager.cpp.
References removeAll().
                     {
        removeAll();
}
Member Function Documentation
WorldEntity & Entity::Loader::loadEntity (EntityInfo * entityInfo) [private]
Creates the worldEntity using the provided factory and returns a reference to it.
Definition at line 131 of file EntityManager.cpp.
References Entity::EntityFactory::loadEntity(), Entity::EntityInfo::m_Name, Entity::EntityInfo::m_XMLFile, and Entity::EntityInfo::mp_Factory.
Referenced by EntityManager::createEntity().
{
        std::cout << "calling factory for " << entityInfo->m_Name << " with xml file " << entityInfo->m_XMLFile << "\n";
        std::cout.flush();
        return entityInfo->mp_Factory->loadEntity(entityInfo->m_XMLFile);
}
Entity::EntityFactory * Entity::Loader::getFactory (const std::string & type) [private]
Returns the factory pointer given a type name string. This should be used by EntityManager while loading Entities in.
Definition at line 120 of file EntityManager.cpp.
References m_FactoryMap.
Referenced by EntityManager::addNewDefinitions(), and EntityManager::init().
{
        //Find the Factory in the map for this type.
        Entity::TypeFactoryMap::iterator factoryItr = m_FactoryMap.find(type);
        //If the type isn't already in the map, insert and return true
        if(factoryItr == m_FactoryMap.end()){
                return NULL;
        }
        return factoryItr->second;
}
bool Entity::Loader::registerFactory (const std::string & type, EntityFactory * factory) [private]
Registers a factory and type into the Loader. These are hard coded in the EntityManager and might always be. Factories must be loaded before that type can be created. There should not be multiple factories for a single type. The first type given will be the only one registered. Once a factory is loaded it can be forgotten about and will be deleted by the Loader.
Definition at line 139 of file EntityManager.cpp.
References m_FactoryMap.
Referenced by EntityManager::init().
{
        //Find the Factory in the map for this type.
        Entity::TypeFactoryMap::iterator factoryItr = m_FactoryMap.find(type);
        //If the type isn't already in the map, insert and return true
        if(factoryItr == m_FactoryMap.end()){
                m_FactoryMap.insert(make_pair(type, factory));
                return true;
        }
        //Type was already associated with some factory
        return false;
}
bool Entity::Loader::remove (const std::string & type) [private]
Removes the factory associated with the given type. Returns false if that type did not have a factory.
Definition at line 97 of file EntityManager.cpp.
References m_FactoryMap.
{
        //Find the Factory in the map for this type.
        Entity::TypeFactoryMap::iterator factoryItr = m_FactoryMap.find(type);
        //If the type isn't already in the map, return false
        if(factoryItr == m_FactoryMap.end()){
                return false;
        }
        delete factoryItr->second;
        m_FactoryMap.erase(factoryItr);
        return true;
}
void Entity::Loader::removeAll () [private]
Removes all registered factories and frees up their memory.
Definition at line 109 of file EntityManager.cpp.
References m_FactoryMap.
Referenced by EntityManager::shutdown(), and ~Loader().
{
        Entity::TypeFactoryMap::iterator factoryItr;
        Entity::TypeFactoryMap::iterator factoryItrEnd = m_FactoryMap.end();
        for(factoryItr = m_FactoryMap.begin(); factoryItr != factoryItrEnd; ++factoryItr)
        {
                delete factoryItr->second;
        }
        m_FactoryMap.clear();
}
Friends And Related Function Documentation
friend class ::EntityManager [friend]
Definition at line 42 of file EntityManager.h.
Member Data Documentation
TypeFactoryMap Entity::Loader::m_FactoryMap [private]
Maps type strings to the factory pointer to use for that type.
Definition at line 44 of file EntityManager.h.
Referenced by getFactory(), registerFactory(), remove(), and removeAll().
The documentation for this class was generated from the following files:
C:/Users/chase/Desktop/game2/edge/bouncibility/include/EntityManager.h
C:/Users/chase/Desktop/game2/edge/bouncibility/src/EntityManager.cpp