Bouncibility: LevelManager Class Reference
LevelManager Class Reference
LevelManager organizes the transition of levels. It The current level should be retrieved from LevelManager. It loads in the given XML file for the global defintion of levels. It tells the entitymanager how to initialize.
#include <LevelManager.h>
Public Member Functions
bool init (irr::IrrlichtDevice *device, const std::string &XMLScenarioDefinition)
Initialize the LevelManager system. Provide the filename of the XML file that has the definition of the scenario to play. Returns false if failed.
void shutdown ()
shutdown any resources used by the LevelManager.
void reset ()
Reset the system, as if init had just been called.
void reset (const std::string &XMLScenarioDefinition)
Reset the system, initializing with this provided new scenario.
Level & getCurrentLevel () const
Returns a reference to the current level object.
bool goToNext ()
Go to the next level. Handles the updating of UserInterface, etc. Returns false if there is no next.
void repeat ()
Repeat the current level, re-initializing all the variables to what they were at start.
void update ()
Update the level. Calls update on the current level. It also checks if the level has been beaten and the level needs to be changed. Or if the characater has died and there needs to be a repeat of the current level.
void draw ()
Draws the current level. Basically calls draw on the current level object as of now.
bool startGame ()
Static Public Member Functions
static irr::scene::ISceneManager * getSceneManager ()
static irr::IrrlichtDevice * getDevice ()
static irr::video::IVideoDriver * getDriver ()
static irr::newton::IWorld * getPhysicsWorld ()
Public Attributes
friend CSingleton< LevelManager >
Private Member Functions
LevelManager ()
~LevelManager ()
LevelManager (const LevelManager &rhs)
LevelManager & operator= (const LevelManager &rhs)
Private Attributes
std::string scenarioDefinition
LevelList m_Levels
The list of levels in order for this scenario, XML files to each different level definition.
Level * m_CurrentLevel
A handle to the currently instantiated level.
LevelList::iterator m_LevelItr
An iterator for the Level list. Pointing to the current level during game execution.
Static Private Attributes
static irr::video::IVideoDriver * s_Driver = NULL
static irr::scene::ISceneManager * s_Smgr = NULL
static irr::IrrlichtDevice * s_Device = NULL
Detailed Description
LevelManager organizes the transition of levels. It The current level should be retrieved from LevelManager. It loads in the given XML file for the global defintion of levels. It tells the entitymanager how to initialize.
Definition at line 19 of file LevelManager.h.
Constructor & Destructor Documentation
LevelManager::LevelManager () [private]
Definition at line 18 of file LevelManager.cpp.
                           : m_CurrentLevel(NULL){
}
LevelManager::~LevelManager () [private]
Definition at line 22 of file LevelManager.cpp.
References shutdown().
{
        this->shutdown();
}
LevelManager::LevelManager (const LevelManager & rhs) [private]
Member Function Documentation
LevelManager& LevelManager::operator= (const LevelManager & rhs) [private]
bool LevelManager::init (irr::IrrlichtDevice * device, const std::string & XMLScenarioDefinition)
Initialize the LevelManager system. Provide the filename of the XML file that has the definition of the scenario to play. Returns false if failed.
Definition at line 37 of file LevelManager.cpp.
References EntityManager::addNewDefinitions(), CSingleton< EntityManager >::getSingleton(), EntityManager::init(), m_LevelItr, m_Levels, s_Device, s_Driver, s_Smgr, and scenarioDefinition.
Referenced by init(), and reset().
{
        s_Device = device;
        s_Smgr = device->getSceneManager();
        s_Driver = device->getVideoDriver();
        //initialize physics world
        s_World = newton::createPhysicsWorld(s_Device);
        scenarioDefinition =  XMLScenarioDefinition;
        EntityManager::getSingleton().init("./res/entities/global.xml");
        IrrXMLReader* xml = createIrrXMLReader(XMLScenarioDefinition.c_str());
        if (!xml){
                std::cout << "There was an error loading the xml file " << XMLScenarioDefinition << ".\n";
        }
        // strings for storing the data we want to get out of the file
        std::string xmlFile;
        while(xml && xml->read())
        {
                switch(xml->getNodeType())
                {
                case EXN_TEXT:
                        //No text nodes
                        break;
                case EXN_ELEMENT:
                        if (!strcmp("entities", xml->getNodeName())){
                                xmlFile = xml->getAttributeValue("file");
                                EntityManager::getSingleton().addNewDefinitions(xmlFile);
                        }
                        if (!strcmp("level", xml->getNodeName())){
                                xmlFile = xml->getAttributeValue("file");
                                m_Levels.push_back(xmlFile);
                        }
                        break;
                }
        }
        m_LevelItr = m_Levels.begin();
        delete xml;
        return true;
}
void LevelManager::shutdown ()
shutdown any resources used by the LevelManager.
Definition at line 90 of file LevelManager.cpp.
References m_CurrentLevel, m_Levels, and Level::shutdown().
Referenced by main(), reset(), and ~LevelManager().
{
        //shutdown  and delete current level
        m_CurrentLevel->shutdown();
        if (m_CurrentLevel){
                delete m_CurrentLevel;
        }
        s_World->destroyWorld();
        m_CurrentLevel = NULL;
        m_Levels.clear();
}
void LevelManager::reset ()
Reset the system, as if init had just been called.
Definition at line 106 of file LevelManager.cpp.
References init(), s_Device, scenarioDefinition, and shutdown().
{
        this->shutdown();
        this->init(s_Device, this->scenarioDefinition);
}
void LevelManager::reset (const std::string & XMLScenarioDefinition)
Reset the system, initializing with this provided new scenario.
Definition at line 140 of file LevelManager.cpp.
References init(), s_Device, and shutdown().
{
        this->shutdown();
        this->init(s_Device, XMLScenarioDefinition);
}
Level & LevelManager::getCurrentLevel () const
Returns a reference to the current level object.
Definition at line 145 of file LevelManager.cpp.
References m_CurrentLevel.
{
        return *m_CurrentLevel;
}
bool LevelManager::goToNext ()
Go to the next level. Handles the updating of UserInterface, etc. Returns false if there is no next.
Definition at line 121 of file LevelManager.cpp.
References Level::load(), m_CurrentLevel, m_LevelItr, m_Levels, and Level::shutdown().
{
        if (m_CurrentLevel){
                m_CurrentLevel->shutdown();
                delete m_CurrentLevel;
        }
        if (m_LevelItr != m_Levels.end()){
                m_CurrentLevel = new Level();
                m_CurrentLevel->load(*(++m_LevelItr));
                return true;
        }
        else{
                return false;
        }
}
void LevelManager::repeat ()
Repeat the current level, re-initializing all the variables to what they were at start.
Definition at line 111 of file LevelManager.cpp.
References Level::load(), m_CurrentLevel, m_LevelItr, and Level::shutdown().
{
        m_CurrentLevel->shutdown();
        delete m_CurrentLevel;
        m_CurrentLevel = new Level();
        m_CurrentLevel->load(*(m_LevelItr));
}
void LevelManager::update ()
Update the level. Calls update on the current level. It also checks if the level has been beaten and the level needs to be changed. Or if the characater has died and there needs to be a repeat of the current level.
Definition at line 150 of file LevelManager.cpp.
References m_CurrentLevel, Level::status(), and Level::update().
Referenced by main().
{
        //need to check if there needs to a level change.
        //isCompleted should return Level::WAITING_REPEAT or Level::FINISHED or Level::RUNNING or Level::WAITING_START
        s_World->update();
        m_CurrentLevel->update();
        int status = m_CurrentLevel->status();
        /*switch (status){
                case Level::WAITING_REPEAT:
                        this->repeat();
                        break;
                case Level::WAITING_START:
                        //Do nothing for now
                        break;
                case Level::FINISHED:
                        //Need to add something if there is no next.
                        this->goToNext();
                        break;
                case Level::RUNNING:
                        //Do nothing for now
                        break;
        }*/
}
void LevelManager::draw ()
Draws the current level. Basically calls draw on the current level object as of now.
bool LevelManager::startGame ()
Definition at line 26 of file LevelManager.cpp.
References Level::load(), m_CurrentLevel, m_LevelItr, and m_Levels.
Referenced by init().
{
        m_CurrentLevel = new Level();
        m_LevelItr = m_Levels.begin();
        m_CurrentLevel->load(*(m_LevelItr));
        return true;
}
static irr::scene::ISceneManager* LevelManager::getSceneManager () [inline, static]
Definition at line 73 of file LevelManager.h.
References s_Smgr.
Referenced by Level::load(), and Entity::BallFactory::loadEntity().
{
                return s_Smgr;
        }
static irr::IrrlichtDevice* LevelManager::getDevice () [inline, static]
Definition at line 77 of file LevelManager.h.
References s_Device.
{
                return s_Device;
        }
static irr::video::IVideoDriver* LevelManager::getDriver () [inline, static]
Definition at line 81 of file LevelManager.h.
References s_Driver.
{
                return s_Driver;
        }
static irr::newton::IWorld* LevelManager::getPhysicsWorld () [inline, static]
Definition at line 86 of file LevelManager.h.
Referenced by Entity::BallFactory::loadEntity().
{
                return s_World;
        }
Member Data Documentation
irr::video::IVideoDriver * LevelManager::s_Driver = NULL [static, private]
Definition at line 23 of file LevelManager.h.
Referenced by getDriver(), and init().
irr::scene::ISceneManager * LevelManager::s_Smgr = NULL [static, private]
Definition at line 24 of file LevelManager.h.
Referenced by getSceneManager(), and init().
irr::IrrlichtDevice * LevelManager::s_Device = NULL [static, private]
Definition at line 25 of file LevelManager.h.
Referenced by getDevice(), init(), and reset().
std::string LevelManager::scenarioDefinition [private]
Definition at line 29 of file LevelManager.h.
Referenced by init(), and reset().
LevelList LevelManager::m_Levels [private]
The list of levels in order for this scenario, XML files to each different level definition.
Definition at line 31 of file LevelManager.h.
Referenced by goToNext(), init(), shutdown(), and startGame().
Level* LevelManager::m_CurrentLevel [private]
A handle to the currently instantiated level.
Definition at line 33 of file LevelManager.h.
Referenced by getCurrentLevel(), goToNext(), repeat(), shutdown(), startGame(), and update().
LevelList::iterator LevelManager::m_LevelItr [private]
An iterator for the Level list. Pointing to the current level during game execution.
Definition at line 35 of file LevelManager.h.
Referenced by goToNext(), init(), repeat(), and startGame().
friend LevelManager::CSingleton< LevelManager >
Definition at line 42 of file LevelManager.h.
The documentation for this class was generated from the following files:
C:/Users/chase/Desktop/game2/edge/bouncibility/include/LevelManager.h
C:/Users/chase/Desktop/game2/edge/bouncibility/src/LevelManager.cpp