Bouncibility: WorldEntity Class Reference
WorldEntity Class Reference
#include <WorldEntity.h>
Public Member Functions
WorldEntity ()
WorldEntity (int iID)
WorldEntity (int iID, float x, float y, float z)
virtual ~WorldEntity ()
void setLocation (float x, float y, float z)
irr::scene::ISceneNode * entity ()
virtual void collide (const std::string &material1, const std::string &material2)
Method called by PhysicsManager if this node said it was interested in hearing about collision between material1 and material2.
int getID ()
void setID (int iID)
irr::scene::ISceneNode * getSceneNode ()
void setSceneNode (irr::scene::ISceneNode *sceneNode)
irr::newton::IBody * getPhysicsBody ()
irr::newton::IMaterial * getBodyMaterial ()
irr::scene::IAnimatedMesh * getMesh ()
void setPhysicsBody (irr::newton::IBody *newBody)
void setBodyMaterial (irr::newton::IMaterial *newMaterial)
void setMesh (irr::scene::IAnimatedMesh *newMesh)
virtual void update ()=0
virtual void load ()=0
virtual void changeState (const std::string name)=0
Protected Attributes
float fx
float fy
float fz
int id
irr::scene::ISceneNode * sceneNode
irr::scene::IAnimatedMesh * mesh
irr::newton::IMaterial * physics_material
irr::newton::IBody * physics_body
Detailed Description
Definition at line 16 of file WorldEntity.h.
Constructor & Destructor Documentation
WorldEntity::WorldEntity ()
Definition at line 5 of file WorldEntity.cpp.
References fx, fy, and fz.
                         : sceneNode(NULL), mesh(NULL), physics_material(NULL), physics_body(NULL){
        fx = 0;
        fy = 0;
        fz = 0;
}
WorldEntity::WorldEntity (int iID)
Definition at line 12 of file WorldEntity.cpp.
References fx, fy, fz, and setID().
                               : sceneNode(NULL), mesh(NULL), physics_material(NULL), physics_body(NULL){
        setID(iID);
        fx = 0;
        fy = 0;
        fz = 0;
}
WorldEntity::WorldEntity (int iID, float x, float y, float z)
Definition at line 22 of file WorldEntity.cpp.
References setID(), and setLocation().
{
        setID(iID);
        setLocation(x,y,z);
}
WorldEntity::~WorldEntity () [virtual]
Definition at line 19 of file WorldEntity.cpp.
{
}
Member Function Documentation
void WorldEntity::setLocation (float x, float y, float z)
Definition at line 45 of file WorldEntity.cpp.
References fx, fy, and fz.
Referenced by Level::load(), and WorldEntity().
{
        fx = x;
        fy = y;
        fz = z;
}
irr::scene::ISceneNode* WorldEntity::entity ()
virtual void WorldEntity::collide (const std::string & material1, const std::string & material2) [virtual]
Method called by PhysicsManager if this node said it was interested in hearing about collision between material1 and material2.
int WorldEntity::getID ()
Definition at line 32 of file WorldEntity.cpp.
References id.
                      {
        return id;
}
void WorldEntity::setID (int iID)
Definition at line 27 of file WorldEntity.cpp.
Referenced by WorldEntity().
{
        if(iID > 0)
                id = iID;
}
irr::scene::ISceneNode* WorldEntity::getSceneNode () [inline]
Definition at line 41 of file WorldEntity.h.
References sceneNode.
{
                return sceneNode;
        }
void WorldEntity::setSceneNode (irr::scene::ISceneNode * sceneNode)
Definition at line 51 of file WorldEntity.cpp.
Referenced by Entity::BallFactory::loadEntity().
{
        this->sceneNode = sceneNode;
}
irr::newton::IBody* WorldEntity::getPhysicsBody () [inline]
Definition at line 48 of file WorldEntity.h.
References physics_body.
{
                return physics_body;
        }
irr::newton::IMaterial* WorldEntity::getBodyMaterial () [inline]
Definition at line 52 of file WorldEntity.h.
References physics_material.
{
                return physics_material;
        }
irr::scene::IAnimatedMesh* WorldEntity::getMesh () [inline]
Definition at line 56 of file WorldEntity.h.
References mesh.
{
                return mesh;
        }
void WorldEntity::setPhysicsBody (irr::newton::IBody * newBody)
Definition at line 41 of file WorldEntity.cpp.
References physics_body.
Referenced by Entity::BallFactory::loadEntity().
{
        physics_body = newBody;
}
void WorldEntity::setBodyMaterial (irr::newton::IMaterial * newMaterial)
Definition at line 35 of file WorldEntity.cpp.
References physics_material.
Referenced by Entity::BallFactory::loadEntity().
{
        physics_material = newMaterial;
}
void WorldEntity::setMesh (irr::scene::IAnimatedMesh * newMesh)
Definition at line 38 of file WorldEntity.cpp.
References mesh.
Referenced by Entity::BallFactory::loadEntity().
{
        mesh = newMesh;
}
virtual void WorldEntity::update () [pure virtual]
Implemented in Ball.
virtual void WorldEntity::load () [pure virtual]
Implemented in Ball.
virtual void WorldEntity::changeState (const std::string name) [pure virtual]
Implemented in Ball.
Referenced by Level::load().
Member Data Documentation
float WorldEntity::fx [protected]
Definition at line 83 of file WorldEntity.h.
Referenced by setLocation(), and WorldEntity().
float WorldEntity::fy [protected]
Definition at line 84 of file WorldEntity.h.
Referenced by setLocation(), and WorldEntity().
float WorldEntity::fz [protected]
Definition at line 85 of file WorldEntity.h.
Referenced by setLocation(), and WorldEntity().
int WorldEntity::id [protected]
Definition at line 87 of file WorldEntity.h.
Referenced by getID().
irr::scene::ISceneNode* WorldEntity::sceneNode [protected]
Definition at line 89 of file WorldEntity.h.
Referenced by getSceneNode(), and Ball::update().
irr::scene::IAnimatedMesh* WorldEntity::mesh [protected]
Definition at line 90 of file WorldEntity.h.
Referenced by getMesh(), and setMesh().
irr::newton::IMaterial* WorldEntity::physics_material [protected]
Definition at line 91 of file WorldEntity.h.
Referenced by getBodyMaterial(), and setBodyMaterial().
irr::newton::IBody* WorldEntity::physics_body [protected]
Definition at line 92 of file WorldEntity.h.
Referenced by getPhysicsBody(), and setPhysicsBody().
The documentation for this class was generated from the following files:
C:/Users/chase/Desktop/game2/edge/bouncibility/include/WorldEntity.h
C:/Users/chase/Desktop/game2/edge/bouncibility/src/WorldEntity.cpp