Bouncibility: Input::Wiimote Class Reference
Input::Wiimote Class Reference
#include <Inputmanager.h>
Public Member Functions
void toggleRumble ()
float getBatteryLevel ()
bool hasAttachement ()
int * whichLEDs ()
float joystickAngle ()
float joystickMagnitude ()
void toggleLED (int which)
Wiimote ()
virtual ~Wiimote ()
Static Public Attributes
static const int WII_MOVE_HANDS_OUTWARD = 1 << 12
static const int WII_MOVE_HANDS_INWARD = 2 << 12
static const int WII_RIGHT_HAND_UP = 3 << 12
static const int WII_BOTH_HANDS_DOWN = 4 << 12
static const int WII_RIGHT_HAND_RIGHT = 5 << 12
static const int WII_RIGHT_HAND_LEFT = 6 << 12
static const int WII_A_BUTTON = WIIMOTE_BUTTON_A
static const int WII_B_BUTTON = WIIMOTE_BUTTON_B
static const int WII_PLUS_BUTTON = WIIMOTE_BUTTON_PLUS
static const int WII_MINUS_BUTTON = WIIMOTE_BUTTON_MINUS
static const int WII_Z_BUTTON = NUNCHUK_BUTTON_Z
static const int WII_C_BUTTON = NUNCHUK_BUTTON_C
static const int WII_1_BUTTON = WIIMOTE_BUTTON_ONE
static const int WII_2_BUTTON = WIIMOTE_BUTTON_TWO
Protected Member Functions
void handle_event (struct wiimote_t *wm)
void handle_ctrl_status (struct wiimote_t *wm)
bool init (InputDeviceInit &deviceInit)
init() should be overridden by the derived class, it is called in registerDevice() in the InputManager.
bool read ()
read() is called for all devices when getInput() is called in the InputManager. Only returns false when fatal error occurs(hardly ever)
void release ()
release() should be overridden by derived class, it is called by InputManager.
bool buttonStatus (int code) const
buttonStatus() returns if the button represented by the sent code is in a pressed or releaseed state.
bool operator() (int code) const
Protected Attributes
int LEDs [4]
float battery_level
bool attachment
int moteID
wiimote ** wiimotes
bool hands_out
bool hands_in
bool right_hand_up
bool both_hands_down
bool right_hand_right
bool right_hand_left
Friends
class ::InputManager
Detailed Description
Definition at line 75 of file Inputmanager.h.
Constructor & Destructor Documentation
Input::Wiimote::Wiimote ()
Definition at line 189 of file Inputmanager.cpp.
References LEDs.
                      : InputDevice(), battery_level(0), attachment(0), moteID(0), wiimotes(NULL){
        LEDs[0] = LEDs[1] = LEDs[2] = LEDs[3] = false;
}
Input::Wiimote::~Wiimote () [virtual]
Definition at line 193 of file Inputmanager.cpp.
References wiimotes.
                      {
        wiiuse_cleanup(wiimotes, 1);
}
Member Function Documentation
void Input::Wiimote::handle_event (struct wiimote_t * wm) [protected]
Definition at line 170 of file Inputmanager.cpp.
Referenced by read().
{
}
void Input::Wiimote::handle_ctrl_status (struct wiimote_t * wm) [protected]
Definition at line 157 of file Inputmanager.cpp.
Referenced by read().
{
}
bool Input::Wiimote::init (Input::InputDeviceInit & deviceInit) [protected, virtual]
init() should be overridden by the derived class, it is called in registerDevice() in the InputManager.
InputManager passes init() the InputDeviceInit structure that the device was registered with, this structure should contain all the needed initialization information.
Parameters:
deviceInit structure containing initialization information.
Implements Input::InputDevice.
Definition at line 31 of file Inputmanager.cpp.
References init(), moteID, release(), and wiimotes.
Referenced by InputManager::init().
{
        int found, connected = 0;
        //call the base class version first.
        InputDevice::init(deviceInit);
        Input::WiimoteInit *wiimoteInit = ((WiimoteInit*)&deviceInit);
        //wiiuse_startup(WIIUSE_PATH);
        moteID = 1;
        wiimotes =  wiiuse_init(1);
        found = wiiuse_find(wiimotes, 1, 5);
        if (!found)
                return false;
        connected = wiiuse_connect(wiimotes, 1);
        if (connected)
                printf("Connected to %i wiimotes (of %i found).\n", connected, found);
        else {
                printf("Failed to connect to any wiimote.\n");
                return false;
        }
        wiiuse_set_leds(wiimotes[0], WIIMOTE_LED_1 | WIIMOTE_LED_4);
        wiiuse_rumble(wiimotes[0], 1);
        Sleep(200);
        wiiuse_rumble(wiimotes[0], 0);
        wiiuse_motion_sensing(wiimotes[0], 1);
        this->release();
        return true;
}
bool Input::Wiimote::read () [protected, virtual]
read() is called for all devices when getInput() is called in the InputManager. Only returns false when fatal error occurs(hardly ever)
Implements Input::InputDevice.
Definition at line 66 of file Inputmanager.cpp.
References handle_ctrl_status(), handle_event(), Input::InputDevice::read(), and wiimotes.
Referenced by InputManager::getInput().
                       {
        InputDevice::read();
        if (wiimotes == NULL){
                return false;
        }
        if (wiiuse_poll(wiimotes, 1)) {
        /*
         *      This happens if something happened on any wiimote.
         *      So go through each one and check if anything happened.
         */
                int i = 0;
                for (; i < 1; ++i) {
                        switch (wiimotes[i]->event) {
                                case WIIUSE_EVENT:
                                        /* a generic event occured */
                                        handle_event(wiimotes[i]);
                                        break;
                                case WIIUSE_STATUS:
                                        /* a status event occured */
                                        handle_ctrl_status(wiimotes[i]);
                                        break;
                                case WIIUSE_DISCONNECT:
                                        /* the wiimote disconnected */
                                        //handle_disconnect(wiimotes[i]);
                                        break;
                                default:
                                        break;
                        }
                }
        }
        return true;
}
void Input::Wiimote::release () [protected, virtual]
release() should be overridden by derived class, it is called by InputManager.
Implements Input::InputDevice.
Definition at line 103 of file Inputmanager.cpp.
References Input::InputDevice::release().
Referenced by init(), and InputManager::shutdown().
{
        InputDevice::release();
}
bool Input::Wiimote::buttonStatus (int code) const [protected, virtual]
buttonStatus() returns if the button represented by the sent code is in a pressed or releaseed state.
The function will return true if the button represented by the code was pressed at the time of the last input poll. the code needs to be static_cast<> to the type that was passed in. The writer of the derived class should have this information.
Parameters:
code key being polled.
Implements Input::InputDevice.
Definition at line 123 of file Inputmanager.cpp.
References both_hands_down, Input::InputDevice::buttonStatus(), hands_in, hands_out, right_hand_left, right_hand_right, right_hand_up, WII_BOTH_HANDS_DOWN, WII_MOVE_HANDS_INWARD, WII_MOVE_HANDS_OUTWARD, WII_RIGHT_HAND_LEFT, WII_RIGHT_HAND_RIGHT, WII_RIGHT_HAND_UP, and wiimotes.
Referenced by operator()().
{
        InputDevice::buttonStatus(code);
        if (code == Input::Wiimote::WII_MOVE_HANDS_OUTWARD){
                return hands_out;
        }
        else if (code == Input::Wiimote::WII_MOVE_HANDS_INWARD){
                return hands_in;
        }
        else if (code == Input::Wiimote::WII_RIGHT_HAND_UP){
                return right_hand_up;
        }
        else if (code == Input::Wiimote::WII_RIGHT_HAND_LEFT){
                return right_hand_left;
        }
        else if (code == Input::Wiimote::WII_RIGHT_HAND_RIGHT){
                return right_hand_right;
        }
        else if (code == Input::Wiimote::WII_BOTH_HANDS_DOWN){
                return both_hands_down;
        }
                return (wiimotes[0]->btns & code) == code;
}
bool Input::Wiimote::operator() (int code) const [protected]
Definition at line 148 of file Inputmanager.cpp.
References buttonStatus(), and Input::InputDevice::buttonStatus().
{
        InputDevice::buttonStatus(code);
        return buttonStatus(code);
}
void Input::Wiimote::toggleRumble ()
Definition at line 153 of file Inputmanager.cpp.
References wiimotes.
{
        wiiuse_toggle_rumble(wiimotes[0]);
}
float Input::Wiimote::getBatteryLevel ()
Definition at line 175 of file Inputmanager.cpp.
References battery_level, and wiimotes.
{
        wiiuse_status(wiimotes[0]);
        return battery_level;
}
bool Input::Wiimote::hasAttachement ()
Definition at line 185 of file Inputmanager.cpp.
References attachment, and wiimotes.
{
        wiiuse_status(wiimotes[0]);
        return attachment;
}
int * Input::Wiimote::whichLEDs ()
Definition at line 180 of file Inputmanager.cpp.
References LEDs, and wiimotes.
{
        wiiuse_status(wiimotes[0]);
        return LEDs;
}
float Input::Wiimote::joystickAngle ()
Definition at line 162 of file Inputmanager.cpp.
References wiimotes.
{
        return wiimotes[0]->exp.nunchuk.js.ang;
}
float Input::Wiimote::joystickMagnitude ()
Definition at line 167 of file Inputmanager.cpp.
References wiimotes.
{
        return wiimotes[0]->exp.nunchuk.js.mag;
}
void Input::Wiimote::toggleLED (int which)
Friends And Related Function Documentation
friend class ::InputManager [friend]
Reimplemented from Input::InputDevice.
Definition at line 94 of file Inputmanager.h.
Member Data Documentation
const int Input::Wiimote::WII_MOVE_HANDS_OUTWARD = 1 << 12 [static]
Definition at line 77 of file Inputmanager.h.
Referenced by buttonStatus().
const int Input::Wiimote::WII_MOVE_HANDS_INWARD = 2 << 12 [static]
Definition at line 78 of file Inputmanager.h.
Referenced by buttonStatus().
const int Input::Wiimote::WII_RIGHT_HAND_UP = 3 << 12 [static]
Definition at line 79 of file Inputmanager.h.
Referenced by buttonStatus().
const int Input::Wiimote::WII_BOTH_HANDS_DOWN = 4 << 12 [static]
Definition at line 80 of file Inputmanager.h.
Referenced by buttonStatus().
const int Input::Wiimote::WII_RIGHT_HAND_RIGHT = 5 << 12 [static]
Definition at line 81 of file Inputmanager.h.
Referenced by buttonStatus().
const int Input::Wiimote::WII_RIGHT_HAND_LEFT = 6 << 12 [static]
Definition at line 82 of file Inputmanager.h.
Referenced by buttonStatus().
const int Input::Wiimote::WII_A_BUTTON = WIIMOTE_BUTTON_A [static]
Definition at line 83 of file Inputmanager.h.
const int Input::Wiimote::WII_B_BUTTON = WIIMOTE_BUTTON_B [static]
Definition at line 84 of file Inputmanager.h.
const int Input::Wiimote::WII_PLUS_BUTTON = WIIMOTE_BUTTON_PLUS [static]
Definition at line 85 of file Inputmanager.h.
const int Input::Wiimote::WII_MINUS_BUTTON = WIIMOTE_BUTTON_MINUS [static]
Definition at line 86 of file Inputmanager.h.
const int Input::Wiimote::WII_Z_BUTTON = NUNCHUK_BUTTON_Z [static]
Definition at line 87 of file Inputmanager.h.
const int Input::Wiimote::WII_C_BUTTON = NUNCHUK_BUTTON_C [static]
Definition at line 88 of file Inputmanager.h.
const int Input::Wiimote::WII_1_BUTTON = WIIMOTE_BUTTON_ONE [static]
Definition at line 89 of file Inputmanager.h.
const int Input::Wiimote::WII_2_BUTTON = WIIMOTE_BUTTON_TWO [static]
Definition at line 90 of file Inputmanager.h.
int Input::Wiimote::LEDs[4] [protected]
Definition at line 98 of file Inputmanager.h.
Referenced by whichLEDs(), and Wiimote().
float Input::Wiimote::battery_level [protected]
Definition at line 99 of file Inputmanager.h.
Referenced by getBatteryLevel().
bool Input::Wiimote::attachment [protected]
Definition at line 100 of file Inputmanager.h.
Referenced by hasAttachement().
int Input::Wiimote::moteID [protected]
Definition at line 101 of file Inputmanager.h.
Referenced by init().
wiimote** Input::Wiimote::wiimotes [protected]
Definition at line 102 of file Inputmanager.h.
Referenced by buttonStatus(), getBatteryLevel(), hasAttachement(), init(), joystickAngle(), joystickMagnitude(), read(), toggleRumble(), whichLEDs(), and ~Wiimote().
bool Input::Wiimote::hands_out [protected]
Definition at line 103 of file Inputmanager.h.
Referenced by buttonStatus().
bool Input::Wiimote::hands_in [protected]
Definition at line 104 of file Inputmanager.h.
Referenced by buttonStatus().
bool Input::Wiimote::right_hand_up [protected]
Definition at line 105 of file Inputmanager.h.
Referenced by buttonStatus().
bool Input::Wiimote::both_hands_down [protected]
Definition at line 106 of file Inputmanager.h.
Referenced by buttonStatus().
bool Input::Wiimote::right_hand_right [protected]
Definition at line 107 of file Inputmanager.h.
Referenced by buttonStatus().
bool Input::Wiimote::right_hand_left [protected]
Definition at line 108 of file Inputmanager.h.
Referenced by buttonStatus().
The documentation for this class was generated from the following files:
C:/Users/chase/Desktop/game2/edge/bouncibility/include/Inputmanager.h
C:/Users/chase/Desktop/game2/edge/bouncibility/src/Inputmanager.cpp