Bouncibility: Input::Action Class Reference
Input::Action Class Reference
Action maps a button to a behavior.
#include <Inputmanager.h>
Public Member Functions
virtual void reset ()
Resets the state of the Action to default.
void addCode (int code, Input::InputDevice &device)
Adds an additional key or mouse code to trigger this action.
void addCode (std::set< int > &codes, Input::InputDevice &device)
int getAmount ()
Returns the amount the Action has been triggered.
bool isPressed ()
returns true if the Action is currently pressed, false otherwise.
void release ()
Releases the button.
void press ()
Presses the button.
void press (const int amount)
Presses the button the specified amount of times.
void setToggleTime (long timeMill)
Sets the time a BEHAVIOR_DETECT_TAP button should wait before it can be pressed again.
long getToggleTime () const
<Gets the time a BEHAVIOR_DETECT_TAP button should wait before it can be pressed again.
void tap ()
Taps the button. (Presses and Releases the button).
const std::string & getName () const
returns the name given to this Action.
Static Public Attributes
static const int BEHAVIOR_DETECT_PRESS = 1 << 0
When a key is pressed, it will stay pressed until the key has been released.
static const int BEHAVIOR_DETECT_TAP = 1 << 1
When a key is pressed, it is released immediately. Tapped buttons cannot be held down.
static const int BEHAVIOR_DETECT_RELEASE = 1 << 2
When a key is released after being pressed, the action is triggered.
Protected Member Functions
Action (const std::string &sName)
Action (const std::string &sName, int code, InputDevice &device)
Action (const Action &rhs)
Action & operator= (const Action &rhs)
~Action ()
void checkButtonStatus ()
Used by InputManager to check if this Action's button was pressed.
Protected Attributes
const std::string & m_Name
The name of the Action.
int m_Behavior
A behavior flag.
int m_Amount
The amount this Action has been triggered.
int m_State
The current state of the Action.
long m_ToggleTime
Timeout before tapped button can be pressed again.
std::map< std::string,
std::set< std::set< int > > > deviceCodeMap
Static Protected Attributes
static const int STATE_RELEASED = 1 << 1
The button this Action represents is released.
static const int STATE_PRESSED = 1 << 0
The button this Action represents is pressed.
static const int STATE_WAITING_FOR_RELEASE = 1 << 2
The button this Action represents is waiting to be released.
Friends
class InputManager
std::ostream & operator<< (std::ostream &os, const Action &action)
Detailed Description
Action maps a button to a behavior.
The Action class encapsulates a behavior. An action is created with the inputmanager. When creating an action an InputDevice must be specified, as well as a code representing the key that triggers this Action. An Action can have two types of behavior, pressing and tapping. The Action methods are thread safe.
Definition at line 233 of file Inputmanager.h.
Constructor & Destructor Documentation
Input::Action::Action (const std::string & sName) [explicit, protected]
Definition at line 427 of file Inputmanager.cpp.
References reset().
                                          : m_Name(sName), m_ToggleTime(0), m_Amount(0){
        reset();
}
Input::Action::Action (const std::string & sName, int code, Input::InputDevice & device) [explicit, protected]
Definition at line 430 of file Inputmanager.cpp.
References addCode().
                                                                             : m_Name(sName), m_ToggleTime(0), m_Amount(0){
        this->addCode(code, device);
}
Input::Action::Action (const Action & rhs) [protected]
Input::Action::~Action () [protected]
Definition at line 462 of file Inputmanager.cpp.
References reset().
                    {
        reset();
}
Member Function Documentation
virtual void Input::Action::reset () [inline, virtual]
Resets the state of the Action to default.
Definition at line 254 of file Inputmanager.h.
References m_Amount, m_State, and STATE_RELEASED.
Referenced by Action(), addCode(), and ~Action().
{
                        m_State = STATE_RELEASED;
                        m_Amount = 0;
                }
void Input::Action::addCode (int code, Input::InputDevice & device)
Adds an additional key or mouse code to trigger this action.
Definition at line 434 of file Inputmanager.cpp.
References deviceCodeMap, Input::InputDevice::getName(), and reset().
Referenced by Action().
{
        if (deviceCodeMap.find(device.getName()) != deviceCodeMap.end()){
                std::set<std::set<int> > codeList;
                std::set<int> codes;
                codes.insert(code);
                codeList.insert(codes);
                deviceCodeMap.insert(make_pair(device.getName(), codeList));
        }
        else{
                std::set<int> codes;
                codes.insert(code);
                deviceCodeMap[device.getName()].insert(codes);
        }
        reset();
}
void Input::Action::addCode (std::set< int > & codes, Input::InputDevice & device)
Definition at line 450 of file Inputmanager.cpp.
References deviceCodeMap, Input::InputDevice::getName(), and reset().
{
        if (deviceCodeMap.find(device.getName()) != deviceCodeMap.end()){
                std::set<std::set<int > > codeList;
                codeList.insert(codes);
                deviceCodeMap.insert(make_pair(device.getName(), codeList));
        }
        else{
                deviceCodeMap[device.getName()].insert(codes);
        }
        reset();
}
int Input::Action::getAmount ()
Returns the amount the Action has been triggered.
Definition at line 467 of file Inputmanager.cpp.
References BEHAVIOR_DETECT_PRESS, m_Amount, m_Behavior, m_State, STATE_RELEASED, and STATE_WAITING_FOR_RELEASE.
Referenced by isPressed().
{
        int retVal = m_Amount;
    if (retVal != 0) {
                if (m_State == Action::STATE_RELEASED) {
            m_Amount = 0;
        }
                else if (m_Behavior == Action::BEHAVIOR_DETECT_PRESS) {
                        m_State = Action::STATE_WAITING_FOR_RELEASE;
            m_Amount = 0;
        }
    }
    return retVal;
}
bool Input::Action::isPressed ()
returns true if the Action is currently pressed, false otherwise.
Definition at line 486 of file Inputmanager.cpp.
References getAmount().
{
        return(getAmount() != 0);
}
void Input::Action::release ()
Releases the button.
Definition at line 494 of file Inputmanager.cpp.
References BEHAVIOR_DETECT_RELEASE, m_Amount, m_Behavior, m_State, and STATE_RELEASED.
Referenced by checkButtonStatus(), and tap().
{
        if (m_Behavior == Input::Action::BEHAVIOR_DETECT_RELEASE){
                m_Amount += 1;
        }
        m_State = Input::Action::STATE_RELEASED;
}
void Input::Action::press ()
Presses the button.
Definition at line 501 of file Inputmanager.cpp.
Referenced by checkButtonStatus(), and tap().
                       {
        press(1);
}
void Input::Action::press (const int amount)
Presses the button the specified amount of times.
Definition at line 505 of file Inputmanager.cpp.
References BEHAVIOR_DETECT_RELEASE, m_Amount, m_Behavior, m_State, STATE_PRESSED, and STATE_WAITING_FOR_RELEASE.
{
        if (m_State != Action::STATE_WAITING_FOR_RELEASE) {
                if (m_Behavior != Input::Action::BEHAVIOR_DETECT_RELEASE){
                        m_Amount += amount;
                }
                m_State = Action::STATE_PRESSED;
    }
}
void Input::Action::setToggleTime (long timeMill)
Sets the time a BEHAVIOR_DETECT_TAP button should wait before it can be pressed again.
long Input::Action::getToggleTime () const [inline]
<Gets the time a BEHAVIOR_DETECT_TAP button should wait before it can be pressed again.
Definition at line 274 of file Inputmanager.h.
References m_ToggleTime.
                {
                        return m_ToggleTime;
                }
void Input::Action::tap ()
Taps the button. (Presses and Releases the button).
Definition at line 481 of file Inputmanager.cpp.
References press(), and release().
Referenced by checkButtonStatus().
                     {
        press();
        release();
}
const std::string & Input::Action::getName () const
returns the name given to this Action.
Definition at line 490 of file Inputmanager.cpp.
References m_Name.
Referenced by operator<<().
{
        return m_Name;
}
Action& Input::Action::operator= (const Action & rhs) [protected]
void Input::Action::checkButtonStatus () [protected]
Used by InputManager to check if this Action's button was pressed.
Definition at line 514 of file Inputmanager.cpp.
References BEHAVIOR_DETECT_PRESS, BEHAVIOR_DETECT_RELEASE, BEHAVIOR_DETECT_TAP, Input::InputDevice::buttonStatus(), deviceCodeMap, InputManager::getDevice(), CSingleton< InputManager >::getSingleton(), m_Behavior, m_State, press(), release(), STATE_RELEASED, and tap().
{
        //Iterates over devices that this action uses
        std::map<std::string, std::set<std::set<int > > >::iterator deviceIter;
        //This flag says whether to release the button or not.
        bool pushedFlag = false;
        for (deviceIter = deviceCodeMap.begin(); deviceIter != deviceCodeMap.end(); deviceIter++){
                //Get current device to reduce string lookups
                Input::InputDevice& currentDevice = (InputManager::getSingleton().getDevice((*deviceIter).first));
                //Iterates over codes registered with this device for this action.
                std::set<std::set<int> >::iterator codeListIter, codeListIterEnd;
                codeListIterEnd = (*deviceIter).second.end();
                for (codeListIter = (*deviceIter).second.begin(); codeListIter != codeListIterEnd; codeListIter++){
                        //Checks if the code on this device has been pressed.
                        bool simultaneousPress = true;
                        std::set<int>::iterator codeIter;
                        for (codeIter = (*codeListIter).begin(); codeIter != (*codeListIter).end(); codeIter++){
                                if (currentDevice.buttonStatus(*codeIter)){
                                        continue;
                                }
                                else{
                                        simultaneousPress = false;
                                        break;
                                }
                        }
                        if(simultaneousPress){
                                pushedFlag = true;
                                if (m_Behavior == Input::Action::BEHAVIOR_DETECT_PRESS || m_Behavior == Input::Action::BEHAVIOR_DETECT_RELEASE){
                                        this->press();
                                }
                                else if (m_Behavior == Input::Action::BEHAVIOR_DETECT_TAP){
                                        this->tap();
                                }
                        }
                }
        }
        //Releases button if none of the registered codes have been pressed.
        if (!pushedFlag && m_State != Input::Action::STATE_RELEASED){
                this->release();
        }
}
Friends And Related Function Documentation
friend class InputManager [friend]
Definition at line 234 of file Inputmanager.h.
std::ostream& operator<< (std::ostream & os, const Action & action) [friend]
Definition at line 720 of file Inputmanager.cpp.
{
        return os << action.getName();
}
Member Data Documentation
const int Input::Action::BEHAVIOR_DETECT_PRESS = 1 << 0 [static]
When a key is pressed, it will stay pressed until the key has been released.
Definition at line 236 of file Inputmanager.h.
Referenced by checkButtonStatus(), InputManager::getAction(), and getAmount().
const int Input::Action::BEHAVIOR_DETECT_TAP = 1 << 1 [static]
When a key is pressed, it is released immediately. Tapped buttons cannot be held down.
Definition at line 237 of file Inputmanager.h.
Referenced by checkButtonStatus().
const int Input::Action::BEHAVIOR_DETECT_RELEASE = 1 << 2 [static]
When a key is released after being pressed, the action is triggered.
Definition at line 238 of file Inputmanager.h.
Referenced by checkButtonStatus(), press(), and release().
const int Input::Action::STATE_RELEASED = 1 << 1 [static, protected]
The button this Action represents is released.
Definition at line 240 of file Inputmanager.h.
Referenced by checkButtonStatus(), getAmount(), release(), and reset().
const int Input::Action::STATE_PRESSED = 1 << 0 [static, protected]
The button this Action represents is pressed.
Definition at line 241 of file Inputmanager.h.
Referenced by press().
const int Input::Action::STATE_WAITING_FOR_RELEASE = 1 << 2 [static, protected]
The button this Action represents is waiting to be released.
Definition at line 242 of file Inputmanager.h.
Referenced by getAmount(), and press().
const std::string& Input::Action::m_Name [protected]
The name of the Action.
Definition at line 245 of file Inputmanager.h.
Referenced by getName().
int Input::Action::m_Behavior [protected]
A behavior flag.
Definition at line 246 of file Inputmanager.h.
Referenced by checkButtonStatus(), InputManager::createAction(), InputManager::getAction(), getAmount(), press(), and release().
int Input::Action::m_Amount [protected]
The amount this Action has been triggered.
Definition at line 247 of file Inputmanager.h.
Referenced by getAmount(), press(), release(), and reset().
int Input::Action::m_State [protected]
The current state of the Action.
Definition at line 248 of file Inputmanager.h.
Referenced by checkButtonStatus(), getAmount(), press(), release(), and reset().
long Input::Action::m_ToggleTime [protected]
Timeout before tapped button can be pressed again.
Definition at line 249 of file Inputmanager.h.
Referenced by getToggleTime().
std::map<std::string, std::set<std::set<int> > > Input::Action::deviceCodeMap [protected]
Definition at line 250 of file Inputmanager.h.
Referenced by addCode(), and checkButtonStatus().
The documentation for this class was generated from the following files:
C:/Users/chase/Desktop/game2/edge/bouncibility/include/Inputmanager.h
C:/Users/chase/Desktop/game2/edge/bouncibility/src/Inputmanager.cpp