Bouncibility: Level Class Reference
Level Class Reference
The Level class holds everything within a specific level. It loads in all the world entities and updates them. Each level has its own xml file.
#include <Level.h>
Public Member Functions
Level ()
~Level ()
bool load (const std::string &LevelDefinition)
Load the level from the given xml definition. Loads in all entities from the EntityManager and stores them in the entityvector.
void shutdown ()
Releases all resources used. Does not need to delete the entities it has, EntityManager does this.
void update ()
Updates the level and all children.
const std::string & getName ()
Gets the level name.
const std::string & getMusicFileName ()
Gets the music file name.
int getCurrentTime ()
Gets the current level time.
void setCurrentTime (int ctime)
Sets the current level time.
int status ()
return the status of the current level. Used to determine whether to go to now or display restart menu, etc.
void setStatus (int newStatus)
Allows someone else to set the status of this level to FINISHED, WAITING_REPEAT, or any other possible statuses. This would be accessed by the UserInterface or possibly a finished marker worldentity.
Static Public Attributes
static const int WAITING_REPEAT = 1
static const int RUNNING = 2
static const int WAITING_START = 3
static const int FINISHED = 4
static const int STOPPED = 5
Private Attributes
EntityVector m_WorldEntities
Vector to hold all world entities.
EntityVector::iterator m_WorldEntityItr
Iterator for the world entities.
std::string m_LevelName
Level name.
std::string m_XmlFile
Filename of xml definition for this level.
std::string m_LevelFile
Level file name.
std::string m_MusicFile
Filename of music file.
int m_Time
Level timer;.
int m_Status
Current status of level.
int m_StartingX
int m_StartingY
irr::scene::IMesh * mesh
irr::newton::IMaterial * physics_material
irr::newton::IBody * physics_body
Friends
std::ostream & operator<< (std::ostream &os, const Level &level)
Detailed Description
The Level class holds everything within a specific level. It loads in all the world entities and updates them. Each level has its own xml file.
Definition at line 19 of file Level.h.
Constructor & Destructor Documentation
Level::Level () [explicit]
Definition at line 23 of file Level.cpp.
References m_StartingX, m_StartingY, m_Status, m_Time, and WAITING_START.
            {
        m_Status = Level::WAITING_START;
        m_Time = 0;
        m_StartingX = 0;
        m_StartingY = 0;
}
Level::~Level ()
Definition at line 30 of file Level.cpp.
References shutdown().
             {
        this->shutdown();
}
Member Function Documentation
bool Level::load (const std::string & LevelDefinition)
Load the level from the given xml definition. Loads in all entities from the EntityManager and stores them in the entityvector.
Level xml definition format <Level attributes, name, music, time, startingx, starting y, mapfilename> <WorldEntities> <Entity name, xlocation, ylocation, startState/> ... </WorldEntities> </Level>
Definition at line 54 of file Level.cpp.
References WorldEntity::changeState(), EntityManager::createEntity(), LevelManager::getSceneManager(), CSingleton< EntityManager >::getSingleton(), CSingleton< LevelManager >::getSingleton(), m_LevelFile, m_LevelName, m_MusicFile, m_StartingX, m_StartingY, m_Time, m_WorldEntities, m_XmlFile, and WorldEntity::setLocation().
Referenced by LevelManager::goToNext(), LevelManager::repeat(), and LevelManager::startGame().
{
        LevelManager::getSingleton().getSceneManager()->clear();
        std::cout << "loading xml file for a level " << LevelDefinition << "\n";
        irr::io::IrrXMLReader* xml = irr::io::createIrrXMLReader(LevelDefinition.c_str());
        // strings for storing the data we want to get out of the file
        std::string entityName;
        int entityX;
        int entityY;
        std::string entityStartState;
        m_XmlFile = LevelDefinition;
        while(xml && xml->read())
        {
                switch(xml->getNodeType())
                {
                case irr::io::EXN_TEXT:
                        //No text nodes
                        break;
                case irr::io::EXN_ELEMENT:
                        if (!strcmp("level", xml->getNodeName())){
                                m_LevelName = xml->getAttributeValue("name");
                                m_MusicFile = xml->getAttributeValue("music");
                                m_Time = xml->getAttributeValueAsInt("time");
                                m_StartingX = xml->getAttributeValueAsInt("startingx");
                                m_StartingY = xml->getAttributeValueAsInt("startingy");
                                m_LevelFile = xml->getAttributeValue("map");
                        }
                        else if (!strcmp("entity", xml->getNodeName())){
                                entityName = xml->getAttributeValue("name");
                                entityStartState = xml->getAttributeValue("startstate");
                                entityX = xml->getAttributeValueAsInt("xloc");
                                entityY = xml->getAttributeValueAsInt("yloc");
                                std::cout << "loaded in entity attributes for entity " << entityName << "\n";
                                WorldEntity& entity = EntityManager::getSingleton().createEntity(entityName);
                                std::cout << "created entity\n";
                                entity.setLocation((float)entityX, (float)entityY, 0);
                                entity.changeState(entityStartState);
                                std::cout << "changed state\n";
                                m_WorldEntities.push_back(&entity);
                                //WorldEntity is assumed to have been added to the sceneManager by this point by its corresponding factory.
                                //We simply need to add it to as a child to the level scene node outside of the xml reading loop?
                        }
                        break;
                }
        }
        //Load in level now that we have the variables.
        LevelManager::getSingleton().getSceneManager()->loadScene(m_LevelFile.c_str());
        //Adds a firt person shooter camera scene node
        LevelManager::getSingleton().getSceneManager()->addCameraSceneNodeFPS();
        delete xml;
        return true;
}
void Level::shutdown ()
Releases all resources used. Does not need to delete the entities it has, EntityManager does this.
Definition at line 43 of file Level.cpp.
References m_Status, m_WorldEntities, and STOPPED.
Referenced by LevelManager::goToNext(), LevelManager::repeat(), LevelManager::shutdown(), and ~Level().
                    {
        m_WorldEntities.clear();
        m_Status = Level::STOPPED;
}
void Level::update ()
Updates the level and all children.
Definition at line 34 of file Level.cpp.
References m_WorldEntities, and m_WorldEntityItr.
Referenced by LevelManager::update().
{
        ::EntityVector::iterator worldEntityEnd = m_WorldEntities.end();
        for(m_WorldEntityItr = m_WorldEntities.begin(); m_WorldEntityItr != worldEntityEnd; m_WorldEntityItr++){
                (*m_WorldEntityItr)->update();
        }
}
const std::string & Level::getName ()
Gets the level name.
Definition at line 121 of file Level.cpp.
References m_LevelName.
{
        //Returns the name of the level
        return m_LevelName;
}
const std::string & Level::getMusicFileName ()
Gets the music file name.
Definition at line 128 of file Level.cpp.
References m_MusicFile.
{
        //Returns the music file name
        return m_MusicFile;
}
int Level::getCurrentTime ()
Gets the current level time.
Definition at line 135 of file Level.cpp.
References m_Time.
{
        //Returns the current level timer
        return m_Time;
}
void Level::setCurrentTime (int ctime)
Sets the current level time.
Definition at line 142 of file Level.cpp.
References m_Time.
{
        //Sets the level timer
        m_Time = ctime;
}
int Level::status ()
return the status of the current level. Used to determine whether to go to now or display restart menu, etc.
Definition at line 148 of file Level.cpp.
References m_Status.
Referenced by LevelManager::update().
                 {
        return m_Status;
}
void Level::setStatus (int newStatus)
Allows someone else to set the status of this level to FINISHED, WAITING_REPEAT, or any other possible statuses. This would be accessed by the UserInterface or possibly a finished marker worldentity.
Definition at line 152 of file Level.cpp.
References m_Status.
{
        m_Status = newStatus;
}
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const Level & level) [friend]
Definition at line 49 of file Level.cpp.
{
        return os << "Current Level: " << level.m_LevelName << ", Status: " << level.m_Status;
}
Member Data Documentation
EntityVector Level::m_WorldEntities [private]
Vector to hold all world entities.
Definition at line 24 of file Level.h.
Referenced by load(), shutdown(), and update().
EntityVector::iterator Level::m_WorldEntityItr [private]
Iterator for the world entities.
Definition at line 26 of file Level.h.
Referenced by update().
std::string Level::m_LevelName [private]
Level name.
Definition at line 28 of file Level.h.
Referenced by getName(), load(), and operator<<().
std::string Level::m_XmlFile [private]
Filename of xml definition for this level.
Definition at line 30 of file Level.h.
Referenced by load().
std::string Level::m_LevelFile [private]
Level file name.
Definition at line 32 of file Level.h.
Referenced by load().
std::string Level::m_MusicFile [private]
Filename of music file.
Definition at line 34 of file Level.h.
Referenced by getMusicFileName(), and load().
int Level::m_Time [private]
Level timer;.
Definition at line 36 of file Level.h.
Referenced by getCurrentTime(), Level(), load(), and setCurrentTime().
int Level::m_Status [private]
Current status of level.
Definition at line 38 of file Level.h.
Referenced by Level(), operator<<(), setStatus(), shutdown(), and status().
int Level::m_StartingX [private]
Definition at line 40 of file Level.h.
Referenced by Level(), and load().
int Level::m_StartingY [private]
Definition at line 42 of file Level.h.
Referenced by Level(), and load().
irr::scene::IMesh* Level::mesh [private]
Definition at line 44 of file Level.h.
irr::newton::IMaterial* Level::physics_material [private]
Definition at line 45 of file Level.h.
irr::newton::IBody* Level::physics_body [private]
Definition at line 46 of file Level.h.
const int Level::WAITING_REPEAT = 1 [static]
Definition at line 52 of file Level.h.
const int Level::RUNNING = 2 [static]
Definition at line 53 of file Level.h.
const int Level::WAITING_START = 3 [static]
Definition at line 54 of file Level.h.
Referenced by Level().
const int Level::FINISHED = 4 [static]
Definition at line 55 of file Level.h.
const int Level::STOPPED = 5 [static]
Definition at line 56 of file Level.h.
Referenced by shutdown().
The documentation for this class was generated from the following files:
C:/Users/chase/Desktop/game2/edge/bouncibility/include/Level.h
C:/Users/chase/Desktop/game2/edge/bouncibility/src/Level.cpp