Bouncibility: EntityManager Class Reference
EntityManager Class Reference
EntityManager provides an easy and organized way of retrieving entities that were defined via an XML file. It loads in the given XML file for the global defintion of entities. Given an entity string name, it will then provide an instantiation of an WorldEntity and keep track of global IDs and will keep track of the deletion of the WorldEntity.
#include <EntityManager.h>
Public Member Functions
bool init (const std::string &XMLEntityDefinition)
Initialize the Entity system. Provide the filename of the XML file that has the global definition for entities. XML file should be <Entities><Entity name="something", file="something.xml", type="something" /></Entities>.
bool addNewDefinitions (const std::string &XMLEntityDefinition)
Add new entity definitions. This function is the same as init in that it loads in the entity definitions. This allows a user of the class to keep different sets of entities in different definitions and only load in parts of them.
void shutdown ()
shutdown any resources used by the EntityManager.
WorldEntity & createEntity (const std::string name)
Retrieves the entity information for an entity named by the given string. Loads this entity with the correct factory and returns a reference to it.
bool remove (const int entityID)
Deletes an entity identified by the given ID number. This can be called to delete an entity since delete should not be called on WorldEntity. All Entities will be cleaned up when EntityManager is shutdown.
void removeAll ()
Deletes all currently instantiated entities. This would be ideal for moving from level to level. Even the ball should get deleted because it will also be in the next level's definition.
WorldEntity & getEntity (const int entityID)
Returns a reference to an already instantiated WorldEntity object given it's ID, NULL if WorldEntity with ID does not exist.
Public Attributes
friend CSingleton< EntityManager >
Private Member Functions
EntityManager ()
~EntityManager ()
EntityManager (const EntityManager &rhs)
EntityManager & operator= (const EntityManager &rhs)
Private Attributes
Entity::Loader m_Loader
Entity::StrEntityMap m_EntityMap
Maps strings to Entity objects.
Entity::IdEntityMap m_IdEntityMap
Maps integers to instantiated world entities.
Entity::IdEntityMap::iterator m_EntityItr
An iterator for the id entity map.
Static Private Attributes
static int next_ID = 1
Next available ID to assign to the next WorldEntity that is instantiatated.
Detailed Description
EntityManager provides an easy and organized way of retrieving entities that were defined via an XML file. It loads in the given XML file for the global defintion of entities. Given an entity string name, it will then provide an instantiation of an WorldEntity and keep track of global IDs and will keep track of the deletion of the WorldEntity.
Definition at line 107 of file EntityManager.h.
Constructor & Destructor Documentation
EntityManager::EntityManager () [private]
Definition at line 174 of file EntityManager.cpp.
{
}
EntityManager::~EntityManager () [private]
Definition at line 178 of file EntityManager.cpp.
References shutdown().
{
        this->shutdown();
}
EntityManager::EntityManager (const EntityManager & rhs) [private]
Member Function Documentation
EntityManager& EntityManager::operator= (const EntityManager & rhs) [private]
bool EntityManager::init (const std::string & XMLEntityDefinition)
Initialize the Entity system. Provide the filename of the XML file that has the global definition for entities. XML file should be <Entities><Entity name="something", file="something.xml", type="something" /></Entities>.
Definition at line 225 of file EntityManager.cpp.
References Entity::Loader::getFactory(), m_EntityMap, m_Loader, and Entity::Loader::registerFactory().
Referenced by LevelManager::init().
{
        std::cout << "loading xml file with name " << XMLEntityDefinition << "\n";
        //Should register all the factories to each type here!!!!
        this->m_Loader.registerFactory("ball", new Entity::BallFactory());
        irr::io::IrrXMLReader* xml = irr::io::createIrrXMLReader(XMLEntityDefinition.c_str());
        if (!xml){
                std::cout << "There was an error loading the xml file " << XMLEntityDefinition << ".\n";
        }
        // strings for storing the data we want to get out of the file
        std::string name;
        std::string xmlFile;
        std::string type;
        while(xml && xml->read())
        {
                switch(xml->getNodeType())
                {
                case irr::io::EXN_TEXT:
                        //No text nodes
                        break;
                case irr::io::EXN_ELEMENT:
                        if (!strcmp("entity", xml->getNodeName())){
                                Entity::EntityFactory* factory = m_Loader.getFactory(xml->getAttributeValue("type"));
                                if (factory){
                                        Entity::EntityInfo* entityInfo = new Entity::EntityInfo(xml->getAttributeValue("name"), xml->getAttributeValue("file"), factory);
                                        if ((m_EntityMap.insert(make_pair(std::string(xml->getAttributeValue("name")), entityInfo))).second){
                                                std::cout << "added entity with name " << std::string(xml->getAttributeValue("name")) << "\n";
                                                }
                                                else{
                                                        m_EntityMap.clear();
                                                        return false;
                                                }
                                }
                                else{
                                        m_EntityMap.clear();
                                        return false;
                                }
                                        }
                                        break;
                                }
        }
        delete xml;
        return true;
}
bool EntityManager::addNewDefinitions (const std::string & XMLEntityDefinition)
Add new entity definitions. This function is the same as init in that it loads in the entity definitions. This allows a user of the class to keep different sets of entities in different definitions and only load in parts of them.
Definition at line 182 of file EntityManager.cpp.
References Entity::Loader::getFactory(), m_EntityMap, and m_Loader.
Referenced by LevelManager::init().
{
        irr::io::IrrXMLReader* xml = irr::io::createIrrXMLReader(XMLEntityDefinition.c_str());
        // strings for storing the data we want to get out of the file
        std::string name;
        std::string xmlFile;
        std::string type;
        while(xml && xml->read())
        {
                switch(xml->getNodeType())
                {
                case irr::io::EXN_TEXT:
                        //No text nodes
                        break;
                case irr::io::EXN_ELEMENT:
                        if (!strcmp("entity", xml->getNodeName())){
                                name = xml->getAttributeValue("name");
                                xmlFile = xml->getAttributeValue("file");
                                type= xml->getAttributeValue("type");
                        }
                        break;
                }
                Entity::EntityFactory* factory = m_Loader.getFactory(type);
                if (factory){
                        Entity::EntityInfo* entityInfo = new Entity::EntityInfo(name, xmlFile, factory);
                                if ((m_EntityMap.insert(make_pair(name, entityInfo))).second){
                                }
                                else{
                                        m_EntityMap.clear();
                                        return false;
                                }
                }
                else{
                        return false;
                }
        }
        delete xml;
        return true;
}
void EntityManager::shutdown ()
shutdown any resources used by the EntityManager.
Definition at line 276 of file EntityManager.cpp.
References m_EntityMap, m_Loader, Entity::Loader::removeAll(), and removeAll().
Referenced by ~EntityManager().
{
        //Remove all instantiated entities
        removeAll();
        //Remove all EntityInfo
        Entity::StrEntityMap::iterator entityItrEnd = m_EntityMap.end();
        Entity::StrEntityMap::iterator entityItr;
        for(entityItr = m_EntityMap.begin(); entityItr != entityItrEnd; ++entityItr)
        {
                entityItr->second->destroy();
                delete entityItr->second;
        }
        //Remove everything inside the loader
        m_Loader.removeAll();
        m_EntityMap.clear();
}
WorldEntity & EntityManager::createEntity (const std::string name)
Retrieves the entity information for an entity named by the given string. Loads this entity with the correct factory and returns a reference to it.
Definition at line 294 of file EntityManager.cpp.
References Entity::Loader::loadEntity(), m_EntityMap, and m_Loader.
Referenced by Level::load().
{
        //Find the Entity in the Str EntityInfo map for this entity name.
        std::cout << "finding entity with name " << name << "\n";
        Entity::StrEntityMap::iterator entityItr = m_EntityMap.find(name);
        //If the Entity wasn't found, return false
        if(entityItr == m_EntityMap.end()){
                std::cout << "entity not found. throwing exception!\n";
                throw Entity::EntityCreationFailed();
        }
        return(m_Loader.loadEntity(entityItr->second));
}
bool EntityManager::remove (const int entityID)
Deletes an entity identified by the given ID number. This can be called to delete an entity since delete should not be called on WorldEntity. All Entities will be cleaned up when EntityManager is shutdown.
Definition at line 306 of file EntityManager.cpp.
References m_EntityItr, and m_IdEntityMap.
{
        //Find the Entity in the ID map for this entityID.
        m_EntityItr = m_IdEntityMap.find(entityID);
        //If the Entity wasn't found, return false
        if(m_EntityItr == m_IdEntityMap.end())
                return false;
        delete m_EntityItr->second;
        m_IdEntityMap.erase(m_EntityItr);
        return true;
}
void EntityManager::removeAll ()
Deletes all currently instantiated entities. This would be ideal for moving from level to level. Even the ball should get deleted because it will also be in the next level's definition.
Definition at line 318 of file EntityManager.cpp.
References m_EntityItr, and m_IdEntityMap.
Referenced by shutdown().
{
        Entity::IdEntityMap::iterator entityItrEnd = m_IdEntityMap.end();
        for(m_EntityItr = m_IdEntityMap.begin(); m_EntityItr != entityItrEnd; ++m_EntityItr)
        {
                delete m_EntityItr->second;
        }
        m_IdEntityMap.clear();
}
WorldEntity & EntityManager::getEntity (const int entityID)
Returns a reference to an already instantiated WorldEntity object given it's ID, NULL if WorldEntity with ID does not exist.
Definition at line 327 of file EntityManager.cpp.
References m_EntityItr, and m_IdEntityMap.
{
        //Find the entity in the ID map for this entityID
        m_EntityItr = m_IdEntityMap.find(entityID);
        //If the Entity wasn't found, return NULL
        if (m_EntityItr == m_IdEntityMap.end())
                throw Entity::EntityDoesntExist();
        return *(m_EntityItr->second);
}
Member Data Documentation
Entity::Loader EntityManager::m_Loader [private]
Definition at line 111 of file EntityManager.h.
Referenced by addNewDefinitions(), createEntity(), init(), and shutdown().
int EntityManager::next_ID = 1 [static, private]
Next available ID to assign to the next WorldEntity that is instantiatated.
Definition at line 112 of file EntityManager.h.
Entity::StrEntityMap EntityManager::m_EntityMap [private]
Maps strings to Entity objects.
Definition at line 114 of file EntityManager.h.
Referenced by addNewDefinitions(), createEntity(), init(), and shutdown().
Entity::IdEntityMap EntityManager::m_IdEntityMap [private]
Maps integers to instantiated world entities.
Definition at line 116 of file EntityManager.h.
Referenced by getEntity(), remove(), and removeAll().
Entity::IdEntityMap::iterator EntityManager::m_EntityItr [private]
An iterator for the id entity map.
Definition at line 118 of file EntityManager.h.
Referenced by getEntity(), remove(), and removeAll().
friend EntityManager::CSingleton< EntityManager >
Definition at line 126 of file EntityManager.h.
The documentation for this class was generated from the following files:
C:/Users/chase/Desktop/game2/edge/bouncibility/include/EntityManager.h
C:/Users/chase/Desktop/game2/edge/bouncibility/src/EntityManager.cpp