Bouncibility: InputManager Class Reference
InputManager Class Reference
InputManager encapsulates all workings of the InputSystem.
#include <Inputmanager.h>
Public Member Functions
bool init ()
Initialize the input system.
void shutdown ()
shutdown any resources used by the InputManager.
void stopPolling ()
Stops the irrilicht keyboard input system from polling the keyboard. Should be called at beginning of main loop.
void resumePolling ()
Starts the irrilicth keyboard input system to poll the keyboard. Should be called at end of main loop.
MastEventReceiver * getEventReceiver ()
Input::Action * createAction (const std::string name, Input::InputDevice &device, int code, int behaviorFlag=Input::Action::BEHAVIOR_DETECT_PRESS)
Creates an Action with the given parameters and returns it to the caller.
Input::Action * createAction (const std::string name, int behaviorFlag=Input::Action::BEHAVIOR_DETECT_PRESS)
Creates an empty action with no key or mouse codes assigned to it, addCode must be called on the action in order to make this action useful.
bool deleteAction (const std::string &name)
Removes the Action with the given name from the InputManager.
bool getInput ()
Gets input from all the devices and notifies all Actions. Currently unsure if this should be internal or called by the user of InputManager.
Input::Action * getAction (const std::string &name)
Returns a reference to an Action in the actionmap that has already been created.
Input::InputDevice & getDevice (const std::string &name)
Returns a reference to the device in the devicemap with the given name.
void resetAllActions ()
Resets all the registered actions, useful for beginning a level with nothing pressed.
Input::Keyboard & getKeyboard ()
Input::Wiimote & getWiimote ()
Input::KeyboardInit & getKeyboardInit ()
Used to retrieve the keyboard initialization structure to modify settings before calling InputManager::init().
Input::WiimoteInit & getWiimoteInit ()
Public Attributes
friend CSingleton< InputManager >
Private Member Functions
InputManager ()
~InputManager ()
InputManager (const InputManager &rhs)
InputManager & operator= (const InputManager &rhs)
Private Attributes
Input::Keyboard m_Keyboard
provided Keyboard implementation.
Input::Wiimote m_Wiimote
provided Wiimote implementation
Input::KeyboardInit m_KeyboardInit
Input::WiimoteInit m_WiimoteInit
Input::StrActionMap m_ActionMap
Maps strings to Actions.
Input::StrActionMap::iterator m_ActionItr
An iterator for the string action map.
Input::StrDeviceMap m_DeviceMap
Maps strings to devices.
MastEventReceiver * receiver
Detailed Description
InputManager encapsulates all workings of the InputSystem.
Currently the InputManager only uses DirectInput. In the future the Input API used might be decoupled from the InputManager. But at the present time, there are very few other options besides DirectInput.
Definition at line 309 of file Inputmanager.h.
Constructor & Destructor Documentation
InputManager::InputManager () [private]
Definition at line 707 of file Inputmanager.cpp.
                           : receiver(NULL){
}
InputManager::~InputManager () [private]
Definition at line 711 of file Inputmanager.cpp.
References shutdown().
{
        this->shutdown();
}
InputManager::InputManager (const InputManager & rhs) [private]
Member Function Documentation
InputManager& InputManager::operator= (const InputManager & rhs) [private]
bool InputManager::init ()
Initialize the input system.
Definition at line 622 of file Inputmanager.cpp.
References Input::InputDevice::getName(), Input::Keyboard::init(), Input::Wiimote::init(), MastEventReceiver::init(), m_DeviceMap, m_Keyboard, m_KeyboardInit, m_Wiimote, m_WiimoteInit, Input::InputDevice::receiver, and receiver.
Referenced by init().
                       {
        receiver = new MastEventReceiver();
        receiver->init();
        m_Keyboard.receiver = receiver;
        if (!m_Wiimote.init(m_WiimoteInit))
                return(false);
        if (!m_Keyboard.init(m_KeyboardInit))
                return(false);
        Input::InputDevice* pKeyboard = &m_Keyboard;
        Input::InputDevice* pWiimote = &m_Wiimote;
        m_DeviceMap.insert(make_pair(m_Wiimote.getName(), pWiimote));
        m_DeviceMap.insert(make_pair(m_Keyboard.getName(), pKeyboard));
        //return success
        return(true);
}
void InputManager::shutdown ()
shutdown any resources used by the InputManager.
Definition at line 666 of file Inputmanager.cpp.
References m_ActionItr, m_ActionMap, m_Keyboard, m_Wiimote, receiver, Input::Wiimote::release(), Input::Keyboard::release(), and resetAllActions().
Referenced by main(), and ~InputManager().
{
        //Reset all actions, just cause
        resetAllActions();
        //Delete and remove all actions from the map.
        for(m_ActionItr = m_ActionMap.begin(); m_ActionItr != m_ActionMap.end(); ++m_ActionItr)
        {
                delete m_ActionItr->second;
        }
        m_ActionMap.clear();
        //have the keyboard and mouse shut themselves down.
        m_Keyboard.release();
        m_Wiimote.release();
        //delete irrilicht input receiver
        if (receiver){
                delete receiver;
        }
}
void InputManager::stopPolling ()
Stops the irrilicht keyboard input system from polling the keyboard. Should be called at beginning of main loop.
Definition at line 650 of file Inputmanager.cpp.
References MastEventReceiver::endEventProcess(), and receiver.
Referenced by main().
{
        if (receiver){
                receiver->endEventProcess();
        }
}
void InputManager::resumePolling ()
Starts the irrilicth keyboard input system to poll the keyboard. Should be called at end of main loop.
Definition at line 642 of file Inputmanager.cpp.
References receiver, and MastEventReceiver::startEventProcess().
Referenced by main().
{
        if (receiver){
                receiver->startEventProcess();
        }
}
MastEventReceiver * InputManager::getEventReceiver ()
Returns the eventReceiver that needs to be passed to the irrilcht createDevice method
Definition at line 619 of file Inputmanager.cpp.
References receiver.
{
        return receiver;
}
Input::Action * InputManager::createAction (const std::string name, Input::InputDevice & device, int code, int behaviorFlag = Input::Action::BEHAVIOR_DETECT_PRESS)
Creates an Action with the given parameters and returns it to the caller.
Actions are managed by the InputManager, deleteAction is provided if needed, but when the InputManager is shutdown the Actions will be taken care of.
Definition at line 568 of file Inputmanager.cpp.
References m_ActionItr, m_ActionMap, and Input::Action::m_Behavior.
{
        m_ActionItr = m_ActionMap.find(name);
        if(m_ActionItr != m_ActionMap.end()){
                std::set<int> codes;
                codes.insert(code);
                m_ActionItr->second->addCode(codes, device);
                return m_ActionItr->second;
        }
        Input::Action* action = new Input::Action(name, code, device);
        action->m_Behavior = behaviorFlag;
        m_ActionMap.insert(make_pair(name, action));
        return action;
}
Input::Action * InputManager::createAction (const std::string name, int behaviorFlag = Input::Action::BEHAVIOR_DETECT_PRESS)
Creates an empty action with no key or mouse codes assigned to it, addCode must be called on the action in order to make this action useful.
Definition at line 582 of file Inputmanager.cpp.
References m_ActionItr, m_ActionMap, and Input::Action::m_Behavior.
{
        m_ActionItr = m_ActionMap.find(name);
        if(m_ActionItr != m_ActionMap.end()){
                return m_ActionItr->second;
        }
        Input::Action* action = new Input::Action(name);
        action->m_Behavior = behaviorFlag;
        m_ActionMap.insert(make_pair(name, action));
        return action;
}
bool InputManager::deleteAction (const std::string & name)
Removes the Action with the given name from the InputManager.
Definition at line 607 of file Inputmanager.cpp.
References m_ActionItr, and m_ActionMap.
{
        //Find the Action in the map according to the given string
        m_ActionItr = m_ActionMap.find(sActionName);
        //If the Action wasn't found, return false
        if(m_ActionItr == m_ActionMap.end())
                return false;
        delete m_ActionItr->second;
        m_ActionMap.erase(m_ActionItr);
        return true;
}
bool InputManager::getInput ()
Gets input from all the devices and notifies all Actions. Currently unsure if this should be internal or called by the user of InputManager.
Definition at line 686 of file Inputmanager.cpp.
References m_ActionItr, m_ActionMap, m_Keyboard, m_Wiimote, Input::Keyboard::read(), and Input::Wiimote::read().
Referenced by main().
{
        m_Wiimote.read();
        m_Keyboard.read();
        for(m_ActionItr = m_ActionMap.begin(); m_ActionItr != m_ActionMap.end(); ++m_ActionItr)
        {
                m_ActionItr->second->checkButtonStatus();
        }
        return true;
}
Input::Action * InputManager::getAction (const std::string & name)
Returns a reference to an Action in the actionmap that has already been created.
Definition at line 592 of file Inputmanager.cpp.
References Input::Action::BEHAVIOR_DETECT_PRESS, m_ActionItr, m_ActionMap, and Input::Action::m_Behavior.
{
        //Find the Action in the map according to the given string
        m_ActionItr = m_ActionMap.find(name);
        if(m_ActionItr == m_ActionMap.end()){
                Input::Action* action = new Input::Action(name);
                action->m_Behavior = Input::Action::BEHAVIOR_DETECT_PRESS;
                m_ActionMap.insert(make_pair(name, action));
                return action;
        }
        return m_ActionItr->second;
}
Input::InputDevice & InputManager::getDevice (const std::string & name)
Returns a reference to the device in the devicemap with the given name.
Definition at line 656 of file Inputmanager.cpp.
References m_DeviceMap.
Referenced by Input::Action::checkButtonStatus().
{
        //Find the Device in the map according to the given string
        Input::StrDeviceMap::iterator iter = m_DeviceMap.find(name);
        //If the Device wasn't found, return false
        //if(iter == m_DeviceMap.end()) //Don't know how to return a NULL value
                //return NULL;
        return *((*iter).second);
}
void InputManager::resetAllActions ()
Resets all the registered actions, useful for beginning a level with nothing pressed.
Definition at line 700 of file Inputmanager.cpp.
References m_ActionItr, and m_ActionMap.
Referenced by shutdown().
{
        for(m_ActionItr = m_ActionMap.begin(); m_ActionItr != m_ActionMap.end(); ++m_ActionItr)
        {
                m_ActionItr->second->reset();
        }
}
Input::Keyboard& InputManager::getKeyboard () [inline]
Definition at line 367 of file Inputmanager.h.
References m_Keyboard.
{
                return m_Keyboard;
        }
Input::Wiimote& InputManager::getWiimote () [inline]
Definition at line 371 of file Inputmanager.h.
References m_Wiimote.
{
                return m_Wiimote;
        }
Input::KeyboardInit& InputManager::getKeyboardInit () [inline]
Used to retrieve the keyboard initialization structure to modify settings before calling InputManager::init().
Definition at line 375 of file Inputmanager.h.
References m_KeyboardInit.
{
                return m_KeyboardInit;
        }
Input::WiimoteInit& InputManager::getWiimoteInit () [inline]
Definition at line 379 of file Inputmanager.h.
References m_WiimoteInit.
{
                return m_WiimoteInit;
        }
Member Data Documentation
Input::Keyboard InputManager::m_Keyboard [private]
provided Keyboard implementation.
Definition at line 313 of file Inputmanager.h.
Referenced by getInput(), getKeyboard(), init(), and shutdown().
Input::Wiimote InputManager::m_Wiimote [private]
provided Wiimote implementation
Definition at line 315 of file Inputmanager.h.
Referenced by getInput(), getWiimote(), init(), and shutdown().
Input::KeyboardInit InputManager::m_KeyboardInit [private]
Definition at line 317 of file Inputmanager.h.
Referenced by getKeyboardInit(), and init().
Input::WiimoteInit InputManager::m_WiimoteInit [private]
Definition at line 318 of file Inputmanager.h.
Referenced by getWiimoteInit(), and init().
Input::StrActionMap InputManager::m_ActionMap [private]
Maps strings to Actions.
Definition at line 320 of file Inputmanager.h.
Referenced by createAction(), deleteAction(), getAction(), getInput(), resetAllActions(), and shutdown().
Input::StrActionMap::iterator InputManager::m_ActionItr [private]
An iterator for the string action map.
Definition at line 322 of file Inputmanager.h.
Referenced by createAction(), deleteAction(), getAction(), getInput(), resetAllActions(), and shutdown().
Input::StrDeviceMap InputManager::m_DeviceMap [private]
Maps strings to devices.
Definition at line 324 of file Inputmanager.h.
Referenced by getDevice(), and init().
MastEventReceiver* InputManager::receiver [private]
Definition at line 326 of file Inputmanager.h.
Referenced by getEventReceiver(), init(), resumePolling(), shutdown(), and stopPolling().
friend InputManager::CSingleton< InputManager >
Definition at line 333 of file Inputmanager.h.
The documentation for this class was generated from the following files:
C:/Users/chase/Desktop/game2/edge/bouncibility/include/Inputmanager.h
C:/Users/chase/Desktop/game2/edge/bouncibility/src/Inputmanager.cpp