Bouncibility: Input::InputDevice Class Reference
Input::InputDevice Class Reference
InputDevice is the base class for all devices added to the InputManager.
#include <Inputmanager.h>
Public Member Functions
InputDevice ()
virtual ~InputDevice ()
const std::string & getName () const
Protected Member Functions
virtual void release ()=0
release() should be overridden by derived class, it is called by InputManager.
virtual bool init (InputDeviceInit &deviceInit)=0
init() should be overridden by the derived class, it is called in registerDevice() in the InputManager.
virtual bool read ()=0
read() is called for all devices when getInput() is called in the InputManager. Only returns false when fatal error occurs(hardly ever)
virtual bool buttonStatus (int code) const =0
buttonStatus() returns if the button represented by the sent code is in a pressed or releaseed state.
Protected Attributes
std::string m_name
The name of the device.
MastEventReceiver * receiver
A pointer to the Irrilicth input receiver object, initialized by InputManager.
Friends
class Action
class ::InputManager
std::ostream & operator<< (std::ostream &os, const InputDevice &device)
Detailed Description
InputDevice is the base class for all devices added to the InputManager.
Definition at line 32 of file Inputmanager.h.
Constructor & Destructor Documentation
Input::InputDevice::InputDevice ()
Definition at line 23 of file Inputmanager.cpp.
                              : receiver(NULL){
}
Input::InputDevice::~InputDevice () [virtual]
Definition at line 26 of file Inputmanager.cpp.
{
}
Member Function Documentation
void Input::InputDevice::release () [protected, pure virtual]
release() should be overridden by derived class, it is called by InputManager.
Implemented in Input::Wiimote, and Input::Keyboard.
Definition at line 12 of file Inputmanager.cpp.
Referenced by Input::Keyboard::release(), and Input::Wiimote::release().
{
}
bool Input::InputDevice::init (Input::InputDeviceInit & deviceInit) [protected, pure virtual]
init() should be overridden by the derived class, it is called in registerDevice() in the InputManager.
InputManager passes init() the InputDeviceInit structure that the device was registered with, this structure should contain all the needed initialization information.
Parameters:
deviceInit structure containing initialization information.
Implemented in Input::Wiimote, and Input::Keyboard.
Definition at line 7 of file Inputmanager.cpp.
References Input::InputDeviceInit::m_name, m_name, and receiver.
{
        this->m_name = deviceInit.m_name;
        receiver = NULL;
        return true;
}
bool Input::InputDevice::read () [protected, pure virtual]
read() is called for all devices when getInput() is called in the InputManager. Only returns false when fatal error occurs(hardly ever)
Implemented in Input::Wiimote, and Input::Keyboard.
Definition at line 15 of file Inputmanager.cpp.
Referenced by Input::Keyboard::read(), and Input::Wiimote::read().
{
        return true;
}
bool Input::InputDevice::buttonStatus (int code) const [protected, pure virtual]
buttonStatus() returns if the button represented by the sent code is in a pressed or releaseed state.
The function will return true if the button represented by the code was pressed at the time of the last input poll. the code needs to be static_cast<> to the type that was passed in. The writer of the derived class should have this information.
Parameters:
code key being polled.
Implemented in Input::Wiimote, and Input::Keyboard.
Definition at line 19 of file Inputmanager.cpp.
Referenced by Input::Keyboard::buttonStatus(), Input::Wiimote::buttonStatus(), Input::Action::checkButtonStatus(), Input::Keyboard::operator()(), and Input::Wiimote::operator()().
{
        return true;
}
const std::string& Input::InputDevice::getName () const [inline]
Definition at line 69 of file Inputmanager.h.
References m_name.
Referenced by Input::Action::addCode(), InputManager::init(), and operator<<().
{
                        return m_name;
                }
Friends And Related Function Documentation
friend class Action [friend]
Definition at line 34 of file Inputmanager.h.
friend class ::InputManager [friend]
Reimplemented in Input::Wiimote, and Input::Keyboard.
Definition at line 35 of file Inputmanager.h.
std::ostream& operator<< (std::ostream & os, const InputDevice & device) [friend]
Definition at line 716 of file Inputmanager.cpp.
{
        return os << device.getName();
}
Member Data Documentation
std::string Input::InputDevice::m_name [protected]
The name of the device.
Definition at line 38 of file Inputmanager.h.
Referenced by getName(), and init().
MastEventReceiver* Input::InputDevice::receiver [protected]
A pointer to the Irrilicth input receiver object, initialized by InputManager.
Definition at line 40 of file Inputmanager.h.
Referenced by Input::Keyboard::buttonStatus(), InputManager::init(), init(), Input::Keyboard::keyToChar(), and Input::Keyboard::read().
The documentation for this class was generated from the following files:
C:/Users/chase/Desktop/game2/edge/bouncibility/include/Inputmanager.h
C:/Users/chase/Desktop/game2/edge/bouncibility/src/Inputmanager.cpp